### ISSUE TITLE
Improve future reproducibility

### ISSUE THREAD

**Issue by vmx** [filecoin-project/filecoin-phase2#3]
There are several things to make sure the validation of the parameters is still possible in the future. Those things should be done after https://github.com/filecoin-project/filecoin-phase2/issues/2 is resolved.

 - [ ] Replace git dependencies with proper releases
 - [ ] Commit the Cargo.lock file

**Comment by DrPeterVanNostrand** [comment]
Thanks @vmx, both of these changes were added in PR #1.
